### ISSUE TITLE
🚀  add field to prevent workspace deletion 

### ISSUE THREAD

**Issue by EliSzBr** [hashicorp/terraform-cloud-operator#383] opened 2024-04-11 11:25 UTC
### Description
When a workspace CRD is deleted from the cluster, the managed workspace is deleted in terraform cloud.
In the case of namespace deletions, accidents, etc... this could result in unmanaged resources, without access to the state file.

### Potential YAML Configuration
```yaml
.spec:
  destroyOnDeletion: false
```

### References
[workspaceSpec](https://github.com/hashicorp/terraform-cloud-operator/blob/main/docs/api-reference.md#workspacespec)
[destroyOnDeletion in moduleSpec](https://github.com/hashicorp/terraform-cloud-operator/blob/main/docs/api-reference.md#workspacespec:~:text=destroyOnDeletion%20boolean)

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment] 2024-04-17 15:34
Hi @EliSzBr,

Thank you for your proposal. I will close this issue as a duplicate of https://github.com/hashicorp/terraform-cloud-operator/issues/213. Please vote on it.

Thank you!

**Closed by arybolovlev** 2024-04-17 15:34 UTC
