### ISSUE TITLE
🐛 Module finalizer is not removed on destroy run with status 'Planned and finished'

### ISSUE THREAD

**Issue by ThumNet** [hashicorp/terraform-cloud-operator#299] opened 2023-11-10 14:59 UTC
### Operator Version, Kind and Kubernetes Version
 - Operator version: v2.0.0
 - Kind: Module
 - Kubernetes version: v1.26.3

### YAML Manifest File
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: module-sample
spec:
  organization: my-org
  name: module-sample
  token:
    secretKeyRef:
      name: tfc-token
      key: token
  destroyOnDeletion: true
  module:
    source: app.terraform.io/my-org/xx/other
    version: 0.1.7
  variables:
  - name: environment  
  workspace:
    name: some-workspace
```

### Output Log
https://gist.github.com/ThumNet/85f6b14354889d0c3dd294fd938bab80

### Output of relevant `kubectl` commands
N/A

### Steps To Reproduce
1. `kubectl apply -f module.yaml`
2. wait for the terraform plan to finish
3. plan a destroy run in terraform cloud
4. `kubectl delete -f module.yaml`

> Note: this is a simplified scenario. This use case is triggered by argocd application deletion.

### Expected Behavior
The finalizer on the module should be removed, so the kubernetes Module resource also can be removed.

### Actual Behavior
The finalizer is not removed from the module so the resource never gets deleted.

### Additional Context
Screenshot of Terraform cloud that shows 2 destroy runs happened.
1. The first destroy run (step 3)
2. Second destroy run triggered from the operator (step 4)
![image](https://github.com/hashicorp/terraform-cloud-operator/assets/692308/0bd18c12-e70c-4b22-bab0-9ddfd0804a3e)

### References
Looking through the code of the `module_controller.go` the issue might be [this line](https://github.com/hashicorp/terraform-cloud-operator/blob/main/controllers/module_controller.go#L287) where only status 'Applied' is checked.

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by ThumNet** [comment] 2023-11-14 09:54
An update from my end, looking through the [Terraform docs](https://developer.hashicorp.com/terraform/cloud-docs/run/states#completion), I found the 'Planned and finished' is a valid **Completion** state.

> Planned and Finished: terraform plan's output already matches the current infrastructure state, so terraform apply doesn't need to do anything.

**Comment by arybolovlev** [comment] 2023-11-15 08:05
Hi @ThumNet,

Thank you for reporting this issue and spotting the place where it happens! ⭐️

A few things here:

- There is a boolean field `spec.destroyOnDeletion` that specifies whether or not to execute a destroy run when the object is deleted from the Kubernetes, by default it is equal to `false`. This might be helpful in your case.
- Rather than just add the `Planned and finished` state, I think we can do an extra validation and if the latest run was a destroy and it was successful, then we don't need to execute a new one and can simply delete the Kubernetes object.

I will be able to work on this issue next week.

Would be happy to hear your thoughts.

Thanks!

**Comment by ThumNet** [comment] 2023-11-15 11:39
Hi @arybolovlev,

Thank you for the response, below answers to the questions/points:

- We are already using the `destroyOnDeletion` field with value `true`
- Sounds like a good idea to check the latest destroy run status. 
  Please not that in our use case ArgoCD is in the mix, which touches the kubernetes resource, and that causes your operator to log the following
   ```
   "error": "Operation cannot be fulfilled on modules.app.terraform.io \"module-sample\": the object has been modified; 
   please apply your changes to the latest version and try again"
   ```
   Which I believe triggers the second destroy run within a few seconds. 

Let me know if/when I can help, maybe by testing?

Thank you

**Comment by arybolovlev** [comment] 2023-11-15 13:57
Just to confirm, does the `destroyOnDeletion` field work for you? It was designed with similar case in mind. :)

Would that be possible to share more details about your workflow? That would help me to write a proper test.

`the object has been modified` -- this error message means that the operator works with the object version older that the one stored in **etcd**. This usually happens when the object gets modified between read and update calls triggered by the operator. This happens when object `spec` is modified. This is another thing that I want to include in the fix -- change of the `destroyOnDeletion` field should not trigger a new reconciliation event.

**Comment by ThumNet** [comment] 2023-11-15 20:01
Yes, the `destroyOnDeletion` field works for us. Except for the fact that the `destroy` run is triggered twice.

The easiest  way I can reproduce the bug is by simply deleting the terraform Module in an ArgoCD application.

If I would use `kubectl` to remove the Module, the destroy run is only triggered once.

So I suspect ArgoCD is also modifying the Module, I havent yet figured out which field/property is modified or added :(

Hope this helps.

**Comment by arybolovlev** [comment] 2023-11-20 09:58
Hi @ThumNet,

I have resumed working on this issue.

Will that be possible for you to run the following commands and share the output with us?

- `kubectl get module <NAME> -w -o yaml` in one window
- `kubectl delete -f module.yaml` in a separate window
- wait till two deletion are queued and share the output from the first window?

That should help answer what causes the second deletion invocation.

**Comment by ThumNet** [comment] 2023-11-20 12:42
Hi @arybolovlev 

Great that you are working on this issue

Output from the first window is available [here](https://gist.github.com/ThumNet/bf9c67b1dcc18066d10c0dd3745539bf)

Note: because we use argocd in a gitops way the delete is done by closing a PR.

**Comment by arybolovlev** [comment] 2023-11-20 15:12
Thank you, @ThumNet!

It looks like ArgoCD removes Kubernetes objects with the  [`foreground`](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion) propagation policy and that is why reconciliation happens twice within a short period of time.

Here is once the object marked as deleted it has the `foregroundDeletion` finalizer that stays with the object until all child objects get deleted. In our case, it is a configMap and/or Secret that are used to store outputs. At this point, the first reconciliation happens and the Module controllers initialize a new deletion run.

```
  deletionTimestamp: "2023-11-20T12:35:59Z"
  finalizers:
  - module.app.terraform.io/finalizer
  - foregroundDeletion
  generation: 2
```

Once all child objects get deleted, Kubernetes removes the `foregroundDeletion` finalizer and that triggers the second reconciliation. Since that happens fast, it causes `the object has been modified` error message once the first deletion reconciliation wants to update the module object status.

```
  deletionTimestamp: "2023-11-20T12:35:59Z"
  finalizers:
  - module.app.terraform.io/finalizer
  generation: 2
```

I have updated the deletion logic and predicates:
- The Module controller will validate during deletion. If the current run is a deletion run, it will track its state; otherwise, it will create a new deletion run.
- The valid complete statuses are `applied` and `planned_and_finished` and they are validated right after the Module controller gets them.
- Events with the `foregroundDeletion` finalizer will be filtered, and the Module controller will proceed with deletion only when `foregroundDeletion` is not present. This change won't affect `background` and `orphan` propagation policy.

Thank you for reporting this issue and helping with debugging!

**Comment by ThumNet** [comment] 2023-11-22 10:26
@arybolovlev Thank you for the detailed explanation and of course the fix!

Can you give me an indication when this might be released?

**Comment by arybolovlev** [comment] 2023-11-22 16:14
Sure! I will cut a release next week, either 27 or 28 November.

**Comment by ThumNet** [comment] 2023-11-22 19:02
Perfect 👌 
Will install it once released and give feedback here.

Thank you

**Closed** 2023-11-23 13:25 UTC
Labels: bug

**Comment by ThumNet** [comment] 2023-11-30 10:06
@arybolovlev I can confirm the `v2.1.0` fixes the issue :+1: 

Thanks again!

**Comment by arybolovlev** [comment] 2023-12-01 19:56
Thank you for your feedback and assistance with debugging, @ThumNet! Happy to hear the issue has been resolved. :)
